spring.application.name=bank_Project


spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mySQL://localhost:3306/bank_project
spring.datasource.username=root
spring.datasource.password=Vivek@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true